### ISSUE TITLE
Dúvida - Most Used Linguages

### ISSUE THREAD

**Issue by SauloMaia01** [rafaballerini/rafaballerini#20]
Bom Dia Rafa, Tudo bem com vc?

Então eu sou novo nesse meio e fiquei com uma duvida, sei que o GRID do Most Used Linguages é estático, mas o que é preciso para mudar as linguagens que aparecem, hj esta aparecendo apenas HTML 100%.

Desde já fico grato pela paciência.

**Comment by FeGroders** [comment]
Ele muda conforme as linguagens utilizadas nos seus repositórios aqui no GitHub. O seu está mostrando apenas HTML porque você possui apenas um repositório feito utilizando HTML, quando você criar mais repo's com outras linguagens ele irá se atualizar automaticamente

**Comment by SauloMaia01** [comment]
> Ele muda conforme as linguagens utilizadas nos seus repositórios aqui no GitHub. O seu está mostrando apenas HTML porque você possui apenas um repositório feito usando HTML, quando você criar mais repo's com outras linguagens ele irá se atualizar automaticamente

Obrigado pelas informações amigo.
