### ISSUE TITLE
Vim pelo vídeoo

### ISSUE THREAD

**Issue by Lizzard-byte** [rafaballerini/rafaballerini#4]
Tmj

**Comment by dudadudadudaaa** [comment]
Parabéns pelo seu canal no YouTube, e por seu trabalho, você é uma inspiração para todas as meninas e mulheres dessa área, muito obrigada!

**Comment by BCARRIEL** [comment]
Muito Legal o Canal...Congratulations!

**Comment by Moises788** [comment]
Eu amei essa dica <3

**Comment by CaioSimioni** [comment]
Muito legal o vídeo  <3

**Comment by IngridFerreira93** [comment]
Parabéns pelo conteúdo! <3

**Comment by risoares19** [comment]
Rafa sua didática é mt boa , parabéns

**Comment by KetlinMouzinho** [comment]
Parabéns pela abordagem da linguagem e toda a sua didática em ensinar. <3 Arrasa demais!!!!!!!!!!!

**Comment by AndersonC75** [comment]
Adorei

**Comment by susanalexiaa** [comment]
Estou amando te acompanhar no canal ❤️ muito obrigada Rafa ❤️

**Comment by edward-mn** [comment]
Show dms !! 👏🏼

**Comment by Tattylima** [comment]
✨🤩

**Comment by ImBeaax** [comment]
10

**Comment by karinkau** [comment]
**Parabéns!!** Sua aula foi bem esclarecedora. Com suas dicas criei meu perfil. obrigada!

**Comment by CainanFlix** [comment]
Obrigado. Esclarecedor seu video.. parabens

**Comment by isem49** [comment]
Achei bastante interessante e esclarecedor  ^-^
